### ISSUE TITLE
카카오 메인 페이지 작성

### ISSUE THREAD

**Issue by mrwebc** [mvcweb75/kakaotalk#1]
애니메이트 메뉴UI

메인배너
   - 페이드 효과
   - 오토 플레이

지역선택 - 셀렉트박스

**Comment by mrwebc** [comment]
메인배너에 인디케이터와 메세지에 애니메이트 효과를 줘서 개선하는건 어떻까요?

**Comment by mvcweb75** [comment]
메인배너에 인디케이터와 메세지에 애니메이트 효과를 줘서 개선하는건 어떻까요?

**Comment by mvcweb75** [comment]
메인배너에 인디케이터와 메세지에 애니메이트 효과를 줘서 개선하는 건 어떨까요?

**Comment by mrwebc** [comment]
아 정말 좋은 생각입니다. 그럼 코드를 작성해 봐야 겠네요.

**Comment by mrwebc** [comment]
아 정말 좋은 생각입니다. 그럼 코드를 작성해 봐야 겠네요.

**Comment by mrwebc** [comment]
아 정말 좋은 생각입니다. 그럼 코드를 작성해 봐야 겠네요.
